### ISSUE TITLE
Support for L5R card lookup

### ISSUE THREAD

**Issue by sjohnc** [dodgepong/stimbot#10]
https://www.fiveringsdb.com seems to be coming along pretty well and has a [published API](https://alsciende.github.io/fiveringsdb/). I'm sure users of stimbot would enjoy support for additional games.

**Comment by dodgepong** [comment]
The main issue is how to make sure users trigger the right thing when they do a search. One possibility is to use new triggering characters other than `[[` and `{{` (such as `<<`), but I feel like that might get out of hand if new games are added.

Instead, I think a more scalable solution is to add support for a specifier token in the search, like so:

`[[net-ready eyes|anr]]`
`{{l5r|watch commander}}`

The specifier could be added to the beginning or end of the search, separating the text with a `|` character, and if no specifier is added, I think a reasonable default would be to assume it's a Netrunner search.

Another solution would be to change the trigger entirely from brackets to independent commands:

`!anrcard estelle moon`
`!l5rcard hida kisada`

This may be easier to understand, but reduces the utility of using the triggers in a sentence, and possibly a bit more awkward to type for some people. I could see it both ways.

**Comment by jdcowf** [comment]
FWIW, I'm personally a fan of {{l5r|...}} with searches defaulting to ANR, tagging mid sentience is a very nice feature

**Comment by rholden** [comment]
I've started a script based on the hubot-netrunnerdb-cards.coffee script for l5r at https://github.com/rholden/steve-the-bioroid/blob/master/scripts/hubot-fiveringsdb-cards.coffee

but I took the alternate character << and (( approach.

It is in no way complete.

**Comment by dodgepong** [comment]
This has now been implemented. You can search for cards with `[[l5r|cardname]]`, `[[cardname|l5r]]` ,`!l5r cardname` or `!l5rcard cardname`, and you can search for card images with `{{l5r|cardname}}` or `{{cardname|l5r}}`.
